sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: TTzN52MASQww4kQ+NDO90dRCN84hjbCxQI+AJTp1p7lp5MBJ5ahzH3CtQqn/nTR9l6fyDqCfb5+wCbS/EzSJxg8Ty11hpbkRQNo4mZTh5ZvP9TmD/qeVNCVH5eECNjYa9XCM246zk9Y/BHZLjKemOFKErznOGSz93rwDI/7l23P1jnlpPhG0lNTm8tvv9r7g2gE1i9VIiBhFM6OYz9eCSUYep1MavEGmTq0gDWBtZdriHssaa5EYo3CnrVBKYKXKI+WDGKc9XlFiqttqnEYHlNW3HDRRjE8Wn/K+G1vm960HDh3uxc45q3RxeRHR0B3XiFtgTnfMyWPIUt1GCr3TixY9LZ0POR8YVLcApPdTOipJ37tPMc4SqxkoRumBUN3HWozzI2dIokG93OomeRoA5MzpGLfYD/06w8IxqztmcDMi0TvF3mL3WL2gp0S9ixGzAW3fGF4EpB8VKnkSi2rDypC4vgsQu3gYeq9xpwP5kYrIdJrCh/WiHfBxs3ahtzbE7859qpHY85mx99EUVnTjLOqgokxVESX1EBLAyu9jl+21R5Rl3cyvP58UjSSgBIlX8eqLJyFc3x9qK06kgYR75AP05GCkibfmnGQvDqwW9aQkEFWk4FkyfV1OV17AXlTjqk9cnwE/I9AxX+EDP8zxCQR9sNhybimnIRSL0CYbC94=
  - secure: vWZJhT9vbvDEr6u4fp7KZIPR1bAAF07/Yy3wVR/zM+0RbD2OaGWL2JV8nAmu/7yjnb/oMsnvZ35LMUnBBw58HALyySibhsHfiGIGq995v3ZVPu5PzuTE/EkX7pbNPPc7enu3+34YQqYJ+FQyYgzWmbe+C+q8bU88jeONgqA85pzWng7m/GmVD2m3PrWAwTmzpEq3XXqXAZGpXoP4yvAdfZeOr9byuUdBtJ4w2ymVw6p4R+VUuqn3I8G4Likk3Z74pQ1SF+Mvpnqhe1ZGtcTHJTm/dVLoTw26ONLzObPYnBJTp8H1jfbHPX0Xjih35Esh0t0ibopSatdjqyBZ9H7ZjnQcjc89mfGyO8M7kPLX/dvlg1NqZ45TNtDRSG04eRT2vAji7fl0qdGrWBsMFyfaiPp2vYC0qY6kYErmglmm1ykjfM7D+YtSY6U1UeLWPS8/hdhDBau9NmejFuSPsJ4zKqCr9SdCy1NRKMyKQj0rKYwaZxTdu87fyYAWTvKDhY5ca9NFysGf4YsnHKwcWcXEkkFh0oUqhQ5XzkzYX9/Js31tNE316q5RQsIMwpcG6gjP7sDdSnfZCvZp8YkoKK4/zDxP3S8Iy5rDPlj9M+s1uPWDjCnvgb/CL4eHHKBrReVy4Kv63HAfZJuE4cMEwBr9+v7ZuSSyQJXP9NhR3nBATJQ=
